
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    container_name: api
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001

  ui:
    image: ui
    container_name: ui
    depends_on:
      - api
    build:
      context: hospitalmanagement
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

volumes:
  mongo_volume: